### ISSUE TITLE
✨ FEAT: EditCard

### ISSUE THREAD

**Issue by seokjun-ko** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#1]
## 💡  Feature Issue

카드를 편집하는 기능과 관련한 개발

| 이슈 내용 | EditCard |
| :--- | :--- |
| 마감 기한 | 2023.07.19 |

## ✅ To-do

- [x] EditCardView
- [x] [Optional] ViewModel
- [x] [Optional] Model
- [x] 스포이드로 카드 색상 변경
- [x] 카드 색상 변경 시, 가사 컨테이너 색상 자동 변경
- [x] 카드 색상 변경 시, 가사 텍스트 색상 자동 변경
