### ISSUE TITLE
♻️REFACTOR: 수정해야할 부분

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#124]
### 2. 온보딩 사진 안뜸
![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-RUN/assets/93391058/95e2df92-9c97-4a20-9cbd-f6a5978fcd57)

### 3. EditCardView 버튼 위치 수정
![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-RUN/assets/93391058/ab822363-0437-453c-b959-f4560abf183e)

### 4. CompleteCardView 버튼 위치 수정
![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-RUN/assets/93391058/996e0d71-fcc4-4741-b155-76572241e42c)

| 이슈 내용 | 입력해주세요 |
| :--- | :--- |
| 마감 기한 | yyyy.mm.dd |

## ✅ To-do

- [x] SE 사이즈에서 온보딩 두줄처리
- [x] 온보딩 사진 안뜸
- [x] EditCardView 버튼 위치 수정
- [x] CompleteCardView 버튼 위치 수정
