### ISSUE TITLE
✨ FEAT: SelectLyricsView 구현

### ISSUE THREAD

**Issue by Jin-s-work** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#17]
## 💡  Feature Issue

| 이슈 내용 | 입력해주세요 |
| :--- | :--- |
| 마감 기한 | 2023.07.24 |

## ✅ To-do

- [x] SelectLyricsModel에서 받아온 가사 정제
- [x] SelectLyricsView 구현
- [x] SelectLyricsView 에서 가사 선택 기능 구현
- [x] SelectLyricsView 화면 배경 블러
- [x] SelectLyricsView 에서 선택한 가사 저장하기
