### ISSUE TITLE
✨ FEAT: 가사 선택 개선하기

### ISSUE THREAD

**Issue by Jin-s-work** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#40]
## 💡  Feature Issue

| 이슈 내용 | 입력해주세요 |
| :--- | :--- |
| 마감 기한 | 2023.07.26 |

## ✅ To-do

- [x] 가사 선택 4개까지 되게 하기
- [x] 4개 선택이 되고, 또 다시 선택이 가능하게 하기
- [x] 배경 색에 따라서 글씨 색 바꾸기
