### ISSUE TITLE
🛠️ FIX: 메인 뷰 수정

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#41]
## 💡  Feature Issue

카드 디테일 구현 시 내용 반영

| 이슈 내용 | 메인 뷰 수정 |
| :--- | :--- |
| 마감 기한 | 2023.07.25 |

## ✅ To-do

- [x] 선택한 카드에 맞는 디테일 뷰 출력
- [x] 아카이빙 스택 외의 영역을 선택하면 내비게이션 작동 문제 해결 (아카아빙스택 외의 영역 -> 버튼)
- [x] 내비게이션 스택 첫 이동 튕김 문제 해결
- [x] 삭제 기능
- [ ] 공유 기능
