### ISSUE TITLE
✨ FEAT: MainView 구현

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#7]
## 💡  Feature Issue

| 이슈 내용 | MainView 구현 |
| :--- | :--- |
| 마감 기한 | 2023.07.24 |

## ✅ To-do

- [x] MainView 화면 생성
- [x] ArchiveCardChip 구현
- [x] ArchiveCardChip의 전면상단(-90 ~ 0, 270 ~ 360)만 출력
- [x] ArchiveCardChip 회전 시 햅틱
- [x] ArchiveCardChip 아이템 코어데이터 연결
- [x] CardChip이 4개 미만일 경우 화면 표현 방법 변경
- [x] CardChip 선택 시 디테일뷰 pop-in 애니메이션 효과
- [x] CardChip 디테일뷰 화면 배경 블러
- [ ] CardChip 공유하기 기능
- [x] CardChip 삭제하기 기능
- [ ] CardChip 슬롯 full일 경우 오래된 CardChip부터 삭제
