### ISSUE TITLE
♻️REFACTOR: 노래제목 / 가수이름 특수문자 처리

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MC3-Team13-RUN#84]
## 💡  Feature Issue
노래제목과 가수 이름의 특수문자들을 처리합니다.

| 이슈 내용 | 노래제목과 가수 이름의 특수문자들을 처리합니다. |
| :--- | :--- |
| 마감 기한 | 계속 업데이트 예정 |

## ✅ To-do

- [x] 노래제목의 온점(.)처리
- [x] 가수 이름 ' 처리 
- [x] 노래 제목 ' 처리
- [x] 노래 제목 ~ 처리
- [x] 노래 제목 + 처리
- [ ] version 나오는 괄호일 경우 괄호 날리기
